### ISSUE TITLE
Plex for kodi recognising True HD as DD sound on first play?

### ISSUE THREAD

**Issue by blazevicm** [pannal/plex-for-kodi#232]
Hello,

I setup PM4k to play my Remuxes. I own Am6b+ box, I installed official stable coreelec 21.3 version and your latest Pm4k 1.0.5e
It looks like my AVR and TV do not play the best when True HD audio is selected as I have to set -175ms audio delay. I do that with the help of  Audio Offset Manager addon. With this Addon, I can set if a video is Dolby Video and if it uses True HD, I can automatically set an offset.

Now an issue is that every time I first open a movie remux with True HD, the client somehow recognizes the sound as DD, not True HD. If I swap out the audio track and back to True HD, then it is properly recognized as True HD.
At first I thought I fixed the issue by disabling the settings > Audio/Subtitles > Treat DTS like AC3, it worked yesterday for 2 tests I did, but the issue is back today. I double checked the setting, it is disabled.

I also have the issue open with the Offset Addon author, but it appears that PM4k could be the culprit
the issue is here with log details
https://github.com/matthane/script.audiooffsetmanager/issues/9#issuecomment-3565342405
Here are the log links posted from the issue above:

Here is the first log:
https://paste.kodi.tv/kiqaxivuje.kodi

Here is what happened:
Enabled debugging
Started Plex
Started the 4k remux of Maverick, however, on the first start, I got the No Signal, not sure why this happened, could be that my hard drives were waking up and it took a bit to load the movie. Selected back out to Plex, then played it the second time, this time it played fine.
Theaddon showed the sound as DD even though I have verified that True HD is playing.

I regenerated a new log with some extra stuff if it might prove to be useful (had to upload it to another site since it is a bit bigger)
https://api.mclo.gs/1/raw/nzQqTUn

What I did:

Enabled logging + enabled that advanced component logging for video, audio and addons
Opened Plex, opened Maveric and Avatar 2022, both on True HD
I swapped to another audio track and then swapped back to True HD on both movies

**Comment by pannal** [comment]
Hmm no, you went into the same rabbit hole as me and thought you needed offsets for certain codecs. You most likely don't.

There's a bug in certain CE builds (on the Ugoos) that requires a short seek back when playing content without a resume point. Otherwise there's a high chance the audio is delayed.

Please use the [1.1.3-beta1 from the forum thread](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21-22/481208/5282), which adds automatic seek back on start to address this issue. You'll notice a short jump at the start of a video, but that fixes the A/V issue completely.

Make sure to reset all audio offsets. It's highly likely you don't need any.

**Comment by pannal** [comment]
As for the no signal issue: set wait for refresh rate change in kodi/CE to something sensible like at least 2.5s.

**Comment by pannal** [comment]
I've got a feeling that most of what you described should be fixed then. If not, report back!

**Comment by blazevicm** [comment]
Awesome, the author of the addon added a fix in a beta version that worked, but I will try the 2 things you mentioned here. Thank you very much!

**Comment by pannal** [comment]
You would have arrived at a sensible audio offset for all codecs during testing. But one day later you'd have noticed that the offsets are wrong when you resume videos.

I was also guessing that the audio delay came only from passthrough codecs and tried to optimize for that, but in the end, I killed all offsets, wrote the seek back on start workaround, and have been a happy camper ever since.

**Comment by blazevicm** [comment]
So I set the delay to 2.5 seconds and I am not seeing the no signal any more, it was hit or miss before, but now it looks like it has been resolved, thanks for that!
I have installed the 1.1.3 beta1 version and reset my audio offset, but the issue is still there. I have to use -175 offset for DV True HD on my system

**Comment by blazevicm** [comment]
Another thing with this beta version is that now the movie does not resume, it always restarts from the beginning. Is that the intended feature?

**Comment by matthane** [comment]
Thanks for sharing! Funny enough, I also include an option in my addon to seek back on player start, because I also found that it helped quite a bit for AV sync. Unless there is a difference in how the seek back works with PM4K, I assume that any method of seek back will help the issue? I'm currently using JSON-RPC Player.Seek to initiate my seek backs.

**Comment by pannal** [comment]
> Another thing with this beta version is that now the movie does not resume, it always restarts from the beginning. Is that the intended feature?

Hmm no that sounds like a bug. Can you supply a log with PM4K set to debug, then using the PM4K log uploader addon from the Don't Panic repository?

**Comment by pannal** [comment]
> Unless there is a difference in how the seek back works with PM4K, I assume that any method of seek back will help the issue? I'm currently using JSON-RPC Player.Seek to initiate my seek backs.

We use the internal `xbmc.executebuiltin('Seek({})'.format(relativeSeekSeconds))` in case of CoreELEC/LG, as that uses relative seeking, which is the whole concept of the Alternate Seek mode that's on by default in PM4K for those platforms. Normal "absolute offset" seeking of `Player().seekTime(target)` is what we normally use, but that leads to quite massive A/V delay issues on those problematic platforms.

Edit: The whole lot of fixes I've done in 1.1.X are mostly targeted towards the Alternate Seek mode, as relative seeking fixes the A/V issues, but now it isn't guaranteed anymore that the player actually seeks, so we're monitoring that and re-seek if necessary. To reduce the "time-drift" when relative seeking with a playing player, in 1.1.X we now pause during a seek and resume when it's done. That's proven to be extremely accurate compared to the previous brute-force method.

**Comment by pannal** [comment]
> I have installed the 1.1.3 beta1 version and reset my audio offset, but the issue is still there. I have to use -175 offset for DV True HD on my system

Interesting. With my HW-Q990C + LG G5 combo (Ugoos directly connected to the soundbar), I don't need any offsets at all.

**Comment by blazevicm** [comment]
> > Another thing with this beta version is that now the movie does not resume, it always restarts from the beginning. Is that the intended feature?
> 
> Hmm no that sounds like a bug. Can you supply a log with PM4K set to debug, then using the PM4K log uploader addon from the Don't Panic repository?

Will see if I can do this tonight. I only tested this with Top Gun Maverick, I would fast forward to 5min mark to test audio as I can check lip sync at 5min mark. I would exit the movie and go back and it would always start from beginning.

**Comment by blazevicm** [comment]
> > I have installed the 1.1.3 beta1 version and reset my audio offset, but the issue is still there. I have to use -175 offset for DV True HD on my system
> 
> Interesting. With my HW-Q990C + LG G5 combo (Ugoos directly connected to the soundbar), I don't need any offsets at all.

I have am6b+ connected to denon x1800h which connects to TCL 646 TV

**Comment by pannal** [comment]
> Will see if I can do this tonight. I only tested this with Top Gun Maverick, I would fast forward to 5min mark to test audio as I can check lip sync at 5min mark. I would exit the movie and go back and it would always start from beginning.

That's not a bug in this case. It's Plex. Simply seeking to 5 minutes doesn't count as "I started watching this". IIRC Plex needs to see you actually play back for at least a minute if I'm not mistaken for it to store a resume point.

> I have am6b+ connected to denon x1800h which connects to TCL 646 TV

Ah OK. Two devices known for having A/V offset requirements, yep. But by using 1.1.3-beta1, you can be _certain_ that the offset you set will be the correct one in the future.

**Comment by blazevicm** [comment]
> > Will see if I can do this tonight. I only tested this with Top Gun Maverick, I would fast forward to 5min mark to test audio as I can check lip sync at 5min mark. I would exit the movie and go back and it would always start from beginning.
> 
> That's not a bug in this case. It's Plex. Simply seeking to 5 minutes doesn't count as "I started watching this". IIRC Plex needs to see you actually play back for at least a minute if I'm not mistaken for it to store a resume point.
> 
> > I have am6b+ connected to denon x1800h which connects to TCL 646 TV
> 
> Ah OK. Two devices known for having A/V offset requirements, yep. But by using 1.1.3-beta1, you can be _certain_ that the offset you set will be the correct one in the future.

Sounds good, will do a more thorough testing on this

**Comment by blazevicm** [comment]
> > Another thing with this beta version is that now the movie does not resume, it always restarts from the beginning. Is that the intended feature?
> 
> Hmm no that sounds like a bug. Can you supply a log with PM4K set to debug, then using the PM4K log uploader addon from the Don't Panic repository?

I just tested this on my other movies that I gave up half way. With the beta version, they all start from beginning. I also let Maverick play on 5+ minutes, plex UI is showing before playing the movie that the movie has started, has that yellow bar. And it still starts all the movies at the beginning with this beta. I'm currently trying to figure out how to send these logs

**Comment by blazevicm** [comment]
Let me know if this works, https://paste.pm4k.eu/ekirenipab not sure if it logged properly. I checked the PM4K and it was set to debug by default.

**Comment by blazevicm** [comment]
I am not on a CPM build, maybe that is the reason?

**Comment by blazevicm** [comment]
Just tested this on this "non-official cpm" build A14 for Kodi 21.3 https://github.com/simonhust/cpm-a14-xbmc/releases + your latest beta. I do not have that issue there, so only the official stable release has it.
I think I will keep this build for now.
Still have the sound delay though which I need to manage through the Audio Offset addon

**Comment by blazevicm** [comment]
@pannal  @matthane Sorry about the pings,, I figured out why the movie starts at the beginning. 
This is due to a combination of 2 beta addons PM4K 1.1.3beta1 https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21-22/481208/5282 and the Audio Offset Manager 1.5.1beta1 from here https://github.com/matthane/script.audiooffsetmanager/issues/9#issuecomment-3565342405
I think the audio offset that triggers at the start is somehow messing with your new PM4K beta and that is why the video restarts. The bug does not happen if I use the Audio Offset manager 1.5.0 version

**Comment by matthane** [comment]
You can disable any of the seek back in my addon settings > Playback Behavior if you are trying to test and isolate the issue. I'm still working on updates to clean up some of the seek back behavior, but try disabling all of them if you are going to use PM4K to handle your seek backs.

**Comment by blazevicm** [comment]
> You can disable any of the seek back in my addon settings > Playback Behavior if you are trying to test and isolate the issue. I'm still working on updates to clean up some of the seek back behavior, but try disabling all of them if you are going to use PM4K to handle your seek backs.

Thanks! I disabled it there and it is working properly now

**Comment by matthane** [comment]
I understand it might just be a conflict that is not worth resolving, but I am noticing as well that with the beta release of PM4K, any of the seek events triggered by Audio Offset Manager seem to trigger the logic in PM4K that starts the video at the beginning. So, if I'm watching a movie and change the audio stream (triggers seek back in Audio Offset Manager if setting enabled), I will see the seek back happen as expected, and then shortly after the seek back from AOM is executed, PM4K executes it's seek back that brings the movie to the start.

My guess is that PM4K is not assuming a player seek command could come from anything other than itself, and assumes it's part of the logic to seek back at the start of the movie when there is no resume point and then executes the rest of the logic which brings the movie/show to the beginning. I'm not exactly sure how it would happen if we are using different functions to execute seek backs, but it's definitely chaining onto them somehow.

**Comment by pannal** [comment]
> My guess is that PM4K is not assuming a player seek command could come from anything other than itself, and assumes it's part of the logic to seek back at the start of the movie when there is no resume point and then executes the rest of the logic which brings the movie/show to the beginning. I'm not exactly sure how it would happen if we are using different functions to execute seek backs, but it's definitely chaining onto them somehow.

We're reacting to onPlaybackSeek events of the Player object. You're triggering that as well, regardless of you using a different API. I might have found why this triggers our seek back to start logic. It's possible it'll be fixed in beta2.

**Comment by blazevicm** [comment]
@pannal @matthane just an update, tested this on latest beta3 PM4K and beta1 Audio Offset Manager, I still need to disable seekback in Audio Manager as the conflict restarts the movie to beginning if audio offset is used.

**Comment by pannal** [comment]
Interesting. Can you set PM4K to DEBUG, reproduce it, then upload a log using PM4K Log Uploader? That'd help! (With beta3)

**Comment by pannal** [comment]
What's the setting within audio offset manager to replicate this? "Seek back upon opening video player"?

Edit: I just enabled that, resumed an item, and yes it seeked back after 4 seconds, but only to the resume point itself, not to the start.

**Comment by blazevicm** [comment]
Do you have audio offset set? Mine is set to -175, only then it starts from begining. Working on the log

**Comment by matthane** [comment]
I think it's essentially any of the seek back options. 

Btw here is the latest beta from my side, I added a debug toggle to make it easier for me to debug and refactored a bit to hopefully allow a fix to be easier to implement if I need to work around something specifically to reduce conflicts. But, this still maintains the seek behavior so I don't expect this to resolve the conflict yet.

[script.audiooffsetmanager-1.6.0-beta1.zip](https://github.com/user-attachments/files/23829758/script.audiooffsetmanager-1.6.0-beta1.zip)

**Comment by pannal** [comment]
I would've thought I fixed this; And no I can't reproduce it. Have -175 set on the particular codec (notification is shown), plus 

<img width="1942" height="1184" alt="Image" src="https://github.com/user-attachments/assets/172ac321-0b1e-4b3a-8579-df8707d3e455" />

Although I'm on my Windows test machine (but with Alternate seek enabled).

It's possible that AOM interferes with seek back on start _very_ early, so it triggers its second seek event maybe.

**Comment by matthane** [comment]
> It's possible that AOM interferes with seek back on start _very_ early, so it triggers its second seek event maybe.

FYI the latest beta I supplied uses a 1-second debounce on AV Change events to make sure that if multiple events happen in succession, it only triggers a seek back after the audio stream is confirmed to be unchanged for 1 second. This is specifically the area where I think the conflict is.

**Comment by pannal** [comment]
@matthane could you simply add a boolean _not_ to interfere with PM4K? I think that'd be a start for most people (you can check whether it's running either via Kodi API or `Window(10000).Property(script.plex.is_active) == "1"`

Maybe I could also set a global prop that tells you: We're done with our initial seek, now you can go ahead and do your stuff.

**Comment by pannal** [comment]
> FYI the latest beta I supplied uses a 1-second debounce on AV Change events to make sure that if multiple events happen in

Yes, onAVChange is nasty. Especially as it's non-trivial. We try to do most onAVStarted, but that doesn't necessarily fire inbetween consecutive playbacks.

**Comment by pannal** [comment]
> Maybe I could also set a global prop that tells you: We're done with our initial seek, now you can go ahead and do your stuff.

Something like: We're `Window(10000).Property(script.plex.preparing_playback)` and `Window(10000).Property(script.plex.playback_prepared)`

**Comment by blazevicm** [comment]
Here is the log
https://paste.pm4k.eu/ekefeyoquy.yaml
What happens:
Seek back on audio format change in Audio Offset Manager is on. My offset for Dolby Vision True HD audio is -175
Play Top Gun Maverick with DV + True HD. 
Audio Offset kicks in and modifies the offset to -175. If this movies is resumed, it will always play from start.
If I pick a different audio that is not offset, it plays fine.

**Comment by matthane** [comment]
Good idea! I can look for your props before submitting any seek backs, if it's not too much of a lift on your end. Otherwise, a quick and dirty solution is I can add a toggle in settings that disables the seekbacks. Something like "PM4K compatibility". Turning it on will just lockout the seekbacks 😆 

edit: In reality, the reason the seek back options exist is to solve the same issues you discovered with the Ugoos and CoreELEC. So they don't need to both exist if PM4K handles them in it's own way to keep the tracks synced.

**Comment by pannal** [comment]
OK, let me break this down (compressed):

```
2025-11-28 16:26:14.618 T:7540     info <general>: script.plexmod: SeekOnStart: Using as SeekOnStart: 316; offset: 316060
2025-11-28 16:26:14.688 T:7540     info <general>: script.plexmod: Player - STARTED
2025-11-28 16:26:14.688 T:7540     info <general>: script.plexmod: SeekHandler: onPlayBackStarted, DP: True
 - later - 
2025-11-28 16:26:15.001 T:7540     info <general>: script.plexmod: SeekHandler: setSubtitles
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: Enabling embedded subtitles at: 0 (English (SRT))
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: Notification: xbmc Info.OnChanged null
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: Notification: xbmc Player.OnPlay {"item":{"title":"Top Gun: Maverick","type":"movie","year":2022},"player":{"playerid":-1,"speed":1}}
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: Player - AVChange: Time: 0.0
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: SeekHandler: onAVChange
2025-11-28 16:26:15.002 T:7540     info <general>: script.plexmod: SeekHandler: Blackout
2025-11-28 16:26:15.096 T:4508     info <general>: Loading skin file: /storage/.kodi/addons/script.plexmod/resources/skins/Main/1080i/script-plex-blackout_dialog.xml, load type: LOAD_ON_GUI_INIT

- here starts the pre-blackout during seek, and we just re-set subtitles (which triggers AVChange), because Kodi is buggy - 

2025-11-28 16:26:15.828 T:7540     info <general>: script.plexmod: SeekHandler: onAVStarted
2025-11-28 16:26:15.832 T:7540     info <general>: script.plexmod: SeekAbsolute: Seeking to 316000
2025-11-28 16:26:16.114 T:7540     info <general>: script.plexmod: SeekHandler: Using reported seek time for getTime: 316000 (-0.021)
2025-11-28 16:26:16.114 T:7540     info <general>: script.plexmod: SeekHandler: onPlayBackSeek: Playing: True, Time: 316.0
2025-11-28 16:26:16.114 T:7540     info <general>: script.plexmod: SeekHandler: onPlayBackSeek: Setting dialog offset to 316000 (seek fix: False, origSOSDiff: 0.0
2025-11-28 16:26:16.114 T:7540     info <general>: script.plexmod: SeekHandler: onPlayBackSeek: SeekOnStart applied: 316000
2025-11-28 16:26:16.114 T:7540     info <general>: script.plexmod: SeekHandler: Setting volume back to 100.
2025-11-28 16:26:16.234 T:7540     info <general>: script.plexmod: SeekHandler: Disabling Blackout
2025-11-28 16:26:16.238 T:7540     info <general>: script.plexmod: Player - AVChange: Time: -0.021
2025-11-28 16:26:16.240 T:7540     info <general>: script.plexmod: SeekHandler: onAVChange
2025-11-28 16:26:16.241 T:7540     info <general>: script.plexmod: SeekDialog: OnAVChange: DPO: 0, offset: 316000
2025-11-28 16:26:16.241 T:7540     info <general>: script.plexmod: Notification: xbmc Player.OnSeek {"item":{"title":"Top Gun: Maverick","type":"movie","year":2022},"player":{"playerid":-1,"seekoffset":{"hours":0,"milliseconds":100,"minutes":5,"seconds":16},"speed":1,"time":{"hours":0,"milliseconds":0,"minutes":5,"seconds":16}}}
2025-11-28 16:26:16.241 T:7540     info <general>: script.plexmod: Notification: xbmc Player.OnAVChange {"item":{"title":"Top Gun: Maverick","type":"movie","year":2022},"player":{"playerid":-1,"speed":1}}
2025-11-28 16:26:16.242 T:7546     info <general>: script.plexmod: Switching audio track - index: 2 to 0 (try: 0)
2025-11-28 16:26:16.281 T:7540     info <general>: script.plexmod: SeekDialog: onFirstInit
2025-11-28 16:26:16.331 T:7540     info <general>: script.plexmod: Got markers: [<Marker:710:b'credits@7305095,final'>]

- at this point we've hit and verified our resume point - 

then, curiously, someone closes our player:

2025-11-28 16:26:16.343 T:7825     info <general>: Closing stream player 1

```

**Comment by pannal** [comment]
> So they don't need to both exist if PM4K handles them in it's own way to keep the tracks synced.

True. But there are non-PM4K users out there.

**Comment by matthane** [comment]
> then, curiously, someone closes our player:

Hmm. I wonder if AOM is targeting the wrong player ID when used with PM4K and submitting seeks to it? I grab the player ID immediately and use that ID to target my seek command. Maybe it's grabbing it too quickly and using a bad value while PM4K is doing it's thing?

**Comment by blazevicm** [comment]
> I think it's essentially any of the seek back options.
> 
> Btw here is the latest beta from my side, I added a debug toggle to make it easier for me to debug and refactored a bit to hopefully allow a fix to be easier to implement if I need to work around something specifically to reduce conflicts. But, this still maintains the seek behavior so I don't expect this to resolve the conflict yet.
> 
> [script.audiooffsetmanager-1.6.0-beta1.zip](https://github.com/user-attachments/files/23829758/script.audiooffsetmanager-1.6.0-beta1.zip)

Currently testing this, get a black screen upon playing a video, had some sync issue, will reboot my box and try a bit more, but so far this beta I had the most issues while others worked great.

**Comment by pannal** [comment]
I'm not sure I've seen the correct portion of the log. Or I really don't get what's happening.

Why is our video player closed immediately after we complete our seek?

**Comment by pannal** [comment]
WAIT!

This is a problem. Since 1.1.3-beta1 we _actively_ _pause_ at the earliest possible time; then issue our seeking (this is true for any seek with Alternate seek (CE/Ugoos) enabled); then resume.

You'll possibly react to ANY of those @matthane 

Sorry for the misquote

**Comment by pannal** [comment]
I think I should implement those two flags. We'll never solve this unless our plugins know about each other. The player doesn't matter.

**Comment by matthane** [comment]
@blazevicm Hmm, ok thanks for letting me know. Maybe I borked something random in that beta. I'll check on my end as well

**Comment by blazevicm** [comment]
> I'm not sure I've seen the correct portion of the log. Or I really don't get what's happening.
> 
> Why is our video player closed immediately after we complete our seek?

Let me know if I should generate new a new log.

**Comment by pannal** [comment]
[script.plexmod.zip](https://github.com/user-attachments/files/23829963/script.plexmod.zip) (reuploaded zip a minute later)

@matthane this does the following:
- if we have a seek to do on start, we set `script.plex.playback_initializing = '1'`
- once we're planning any seek at all (not only seek on start), we set `script.plex.playback_seeking = '1'`
- once we're done with an initial seek or any other seek, we set both to `''`

Because any seek with Alternate seek (CE/LG/Ugoos) will lead to us pausing before seeking, then resuming when done.

I've added state logs for this:
```
util.DEBUG_LOG("HELLO AOM: WE WANT TO SEEK ON START; SETTING AOM PROPERTY initializing: '1'")
util.DEBUG_LOG("HELLO AOM: NOTHING TO DO; SETTING AOM PROPERTY initializing: ''")
util.DEBUG_LOG("HELLO AOM: DONE; SETTING AOM PROPERTY initializing: '', seeking: ''")
util.DEBUG_LOG("HELLO AOM: SEEK REQUESTED; SETTING AOM PROPERTY seeking: '1'")
```

So basically with those properties you know those things:
- when we start a playback and we will immediately issue a pause+seek+resume once we can (this is the initializing + seeking property), or pause+seek+seek+resume, you need to ignore all events until both flags are empty
- when we do a general seek only the seeking property will be set until we're satisfied with the seek position (this will also pause+seek+resume)

**Comment by matthane** [comment]
Hmm, doing some troubleshooting on my end and bumped into a different issue (I think). I've removed my add-on entirely from my system for sake of debugging. On the latest PM4K beta 3, DV P7 FEL playback seems to be somewhat broken. For example, jumping to a new chapter results in no audio and stuttering playback. It doesn't seem like P8 or P7 MEL is affected. I rolled back to latest stable PM4K, and the issue is not present there.

Not sure if a log will reveal this specific issue, but I can look closely as well and pull the log a bit later when I have more time.

**Comment by pannal** [comment]
That's a separate issue. I haven't had any reports yet of beta3 breaking something specifically. I can take a look at your logs, though. You have Alternate seek enabled, as well as all the other bells and whistles (those are on by default)

**Comment by matthane** [comment]
That's great, thank you! I will use your latest zip and play around with it to see if I can get some nice cooperation between the addons. I will also try to get a nice log for the other FEL anomaly.

**Comment by pannal** [comment]
I'll ping the #ugoos-mediaplayer guys on the TRaSH discord. You can also join, so we can get a little faster on this issue, once you have time.

**Comment by pannal** [comment]
> For example, jumping to a new chapter results in no audio and stuttering playback

No audio and stuttering playback, hmm. That should produce _a lot_ of out of sync errors in your log. Watch for those

**Comment by matthane** [comment]
I'm not currently apart of any Discord community related to Ugoos, so I'm not familiar with that one.

I should be able to spend more time this weekend and I'll let you know when I have more info. Thanks for being supportive and adding those outputs for me!

**Comment by pannal** [comment]
Well, feel free to join, or DM me directly via _redacted_, so you don't have to join anything.

**Comment by pannal** [comment]
So far your issue wasn't reproducible by multiple users (CPM A14 and 21.3 community)

**Comment by matthane** [comment]
Thanks for checking, I'll send you a DM on Discord.

Edit: just sent a request, my username there is TheShoxter

**Comment by blazevicm** [comment]
@pannal @matthane   looks like I had the issue even without the AOM addon. Here is the log where the issue was happening to me
https://paste.pm4k.eu/ezusejulos.php-template
What happened: removed AOM addon, rebooted, tested with Maverick. It looks like the issue is only when 7.1 sound is being played. I also get this green tint in DV sometimes https://postimg.cc/NLQYsbRM when trying to play.

However,
restarted Plex second time, and tested the sound again, it appears it is resuming fine. Nothing changed, so weird, so not sure what the hell is happening lol. Maybe some settings got stuck?

Then I installed AOM again (latest beta 1.6 b2 matthane shared here https://github.com/matthane/script.audiooffsetmanager/issues/9#issuecomment-3591916849), configured the offset and rebooted:
On the first play where it was supposed to resume with the AOM with default settings (only -175 TrueHD DV offset) it played fine!
Then, paused, exited, played again, and it resumed again!

So not sure what was the cause there, maybe be installing/reinstalling different versions without reboot got the player into a weird state?

Anyway, the log is the where it was happening, for now, it seems that the issue is resolved for me after removing AOM, rebooting a couple of times. Tested with Avatar 2, the resume is also working fine there. Only got that green screen bug 1 time, not sure if that is PM4K issue or coreelec in general. The issue is rare, so I am not concerned.

Thank you to both of you for making these 2 addons, these 2 are the only ones I use on my home theatre setup :)

**Comment by pannal** [comment]
Thanks for reporting back. 1.1.3-beta4 will implement hints for AOM as to what we're currently doing, so AOM should never interfere anymore with our seeking. Even though you couldn't properly reproduce, this was still worthwhile!

Both addons should now play reasonably well together (once AOM gets released and 1.1.3 stable is out)
