### ISSUE TITLE
Subtitles now showing

### ISSUE THREAD

**Issue by giosann** [pannal/plex-for-kodi#235]
I'm using plex version 1.0.5f from the "don't panic" repository on an Ugoos AM6B+ with coreelec 21.2 Omega (CPM A14)
when i try to play any file with subtitles they don't appear on screen.
I've tried many settings in both coreelec and the plex plugin but to no ultimate avail. Things I've tried include
- configuring a smb mount in coreelec and have the plex plugin use those via a path mapping instead of the http stream
- adding a "Pause during refresh rate change" in coreelec
- in the kodi settings set the subtitle position to "bottom of screen"

At the beginning of playback subs do not work and currently to show them i have to do ether of these things:
A) Disable subs, enable subs. They appear. This unfortunately only until I pause or seek the video and they disappear again.
B) set the video quality to anything different from original. Once the video is transcoding the subtitles appear correctly.

If i go to the file folder manually in the coreelec interface i can play the files with no problem with the integrated player and the subtitles do show correctly.

What can I try to fix this? I would prefer not to have to transcode the video to show the subtitles correctly.

here is the log where I'm testing with "One Battle After Another": https://paste.pm4k.eu/fulacelava

**Comment by pannal** [comment]
Try [1.1.4-beta5](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21-22/481208/5610) please, before investing more time in this issue. I've fixed a long standing problem with embedded subs in there.

**Comment by pannal** [comment]
The fix for this is "seek back on start", which is especially useful/necessary with CoreELEC CPM. I'd kindly suggest you switch to U3k, though: https://github.com/U3knOwn/xbmc/releases, IMHO it's the successor to CPM A14 (based on it, but with a lot of backports from 21.3/22 features and fixes)

**Comment by giosann** [comment]
I've updated to Plex 1.1.4-beta5 and U3k B10 but still no subs.

When you say "seek back on start" you mean doing so manually after a few seconds or some setting?
Unfortunately seeking manually does not fix the issue for me, it's still only disabling/enabling subtitles (temporary fix) or changing the equality of the playback.

Again selecting the movie from the file explorer makes the subs appear correctly

This is the debug log: https://paste.pm4k.eu/hoquwequku
I've tried again with one battle after another and also with 1917 that has pgs subs

---
Just an additional info, I've tried doing a factory reset, reinstalling the beta5 and U3k B10 but it's still the same

**Comment by giosann** [comment]
Updated
plexmod to 1.2.6-beta1.1
CoreElec to p3i T1

unfortunately still no luck with subtitles. I can provide another log if needed but the issue presents the same way

**Comment by giosann** [comment]
In the end it was my own issue on the server-side configuration. A mix of

- the server and client being on different local networks
- not having the client own local network marked in the server settings under Network - LAN Networks
- Having remote access disabled but with "Limit remote stream bitrate" set to 4Mbps (720p)

I noticed how to solve it because i was watching on the TV app and it was playing in 720p.
I found it weird and discovered by enabling stream info that it was transcoding because the maximum bitrate was 4000.
This was doubly weird since i was on LAN. Then i remebered that the TV, like the ugoos where on the same network, a different one from the plex server. from there i found the solution.
